### ISSUE TITLE
Suggestion to add more modifier keys, editing keys and touchpad lock functions

### ISSUE THREAD

**Issue by brandleesee** [caasiu/gnome-shell-extension-KeysIndicator#2]
May I suggest that the following are added as well:

<code>Fn</code> | <code>Ins</code> | <code>Alt Gr</code>

And albeit not a button an indicator for the Touchpad.
This will save me from installing two extensions.

**Comment by caasiu** [comment]
Thanks for your suggestion.

First of all, I use Gdk.Keymap class to map the keyboard. And get_modifier_state() to detect the keys status. 
According to the [Gdk Doc(Gdk.ModifierType)](https://lazka.github.io/pgi-docs/Gdk-3.0/flags.html#Gdk.ModifierType):

> Typical modifier keys are Shift, Control, Meta, Super, Hyper, Alt, Compose, Apple, CapsLock or ShiftLock.

There are no `Fn` | `Ins` keys and both Alt are the same.

To add thoses keys, I have to find a way to map the whole keyboard by using 'key-press-event' signal. Any suggestion?

Secondly, I don't understand what you talk about your Touchpad?

**Comment by brandleesee** [comment]
> There are no Fn | Ins keys and both Alt are the same.

I get your meaning as, yes, FN & Ins are not modifier keys.

However, Alt and Alt Gr are not the same. When setting another language and special characters are used by the 'default' keyboard keys, the original keys can only be inserted/typed using Alt Gr not the normal Alt.

> Any suggestion?

No, because I'm not well versed at the moment. If the issue was on Windows, I would have tried tackling it with AutoHotKey. Linux is a different story.  

> I don't understand what you talk about your Touchpad?

A two-in-one feature of both your extension and [this](https://github.com/mkopta/toggle-touchpad) or [this](https://user501254.github.io/TouchpadIndicator/). Of course, these do not have anything to do with modifiers etc, but thought Caps Lock, Num Lock and Touchpad Indicator would go well together.

**Comment by caasiu** [comment]
> I get your meaning as, yes, FN & Ins are not modifier keys.

According to the [Develper](https://developer.gnome.org/gdk3/stable/gdk3-Keyboard-Handling.html), there is `GdkEventKey.keyval` that can detect plenty of keys included Fn key and other language keyboard keys. But I don't know how to use it.

> However, Alt and Alt Gr are not the same. When setting another language and special characters are used by the 'default' keyboard keys, the original keys can only be inserted/typed using Alt Gr not the normal Alt.

What I mean is both `Alt` will return the same keycode by using get_modifier_state() function, so I can't identify which one is `Alt Gr`.

**Comment by brandleesee** [comment]
Ah, I see. Well, your code as is is good enough.
Thanks nonetheless.

**Comment by gitfineon** [comment]
@brandleesee Maybe you can change the title of this issue to something more specific like: 
"_Add more modifier keys, editing keys and touchpad lock function_" 
and @caasiu can label it as feature request, which may require to change the backend.

**Comment by brandleesee** [comment]
@gitfineon indeed, changed!
