### ISSUE TITLE
suggestion not to hide the icon

### ISSUE THREAD

**Issue by bsdson** [caasiu/gnome-shell-extension-KeysIndicator#3]
current implementation will show and hide icons according to status.
but this moves everything else besides it.
it would be better if it can simply "gray-out" the icon, not "hide" the icon.
Thanks.

**Comment by caasiu** [comment]
I don't think it's a good idea. 
The extension contains 5 icons which will take up a lot of panel's space.
Do you really want that?
Or you can try to change the order of the extension, so it wouldn't move others.

**Comment by caasiu** [comment]
I add Gray-out style on version 2
Have a try :)
Install manually!

**Comment by bsdson** [comment]
just tried, and it works great!
Thank you very much!
ps. I have tried to adjust the position before,
      but it just not work very well,
      and hence makes other icons moves when press/release those keys...
