### ISSUE TITLE
Does not work in native wayland windows

### ISSUE THREAD

**Issue by schaze** [caasiu/gnome-shell-extension-KeysIndicator#4]
Hi,

this is a very usefull extension. However when running a wayland session the indicator icons only work for xwayland windows. (e.g. it works when I am in the chromium window, it will not work when I am in the gnome-terminal, or any native gnome application).
Do you have any intention of also supporting wayland?

Best regards,
schaze

**Comment by caasiu** [comment]
Sorry, schazet

I don't have time recently. Also, I don't know how interact with Gnome.
However, PRs are welcome

regards

**Comment by caasiu** [comment]
Hi, schazet
This extension uses the keymap api, but sadly it doesn't work with native gnome applications.
I find a bug on gnome bugzilla about this issue [Bug 773407](https://bugzilla.gnome.org/show_bug.cgi?id=773407) , which is out of my hands.

**Comment by gitfineon** [comment]
I can reproduce the issue on Ubuntu with GNOME Shell 3.28.1
The indicator icons do not update until focus is removed from an app rendered from wayland directly.

**Comment by schaze** [comment]
I don't think this will get resolved as it is. Closing this issue as to not have zombies laying around.
