### ISSUE TITLE
undeclared variable styleId

### ISSUE THREAD

**Issue by tobias47n9e** [caasiu/gnome-shell-extension-KeysIndicator#5]
Just saw this error in Gnome Shell 3.22

```
.local/share/gnome-shell/extensions/keys-indicator@caasiu.github.com/extension.js 321]: assignment to undeclared variable styleId
```

**Comment by caasiu** [comment]
I'm on Arch + Gnome 3.22
Both pop-up and Gray-out style don't have this issue

Can you show me how you get this issue?

**Comment by tobias47n9e** [comment]
Couldn't reproduce it today. But it is probably caused by `styleId` not being declared here:

https://github.com/caasiu/gnome-shell-extension-KeysIndicator/blob/master/keys-indicator%40caasiu.github.com/extension.js#L24

Odd that it doesn't appear each time the extension is loaded.

**Comment by caasiu** [comment]
It's my carelessness! 
Thanks.

**Comment by tobias47n9e** [comment]
Thanks for fixing the issue!
