### ISSUE TITLE
Enhancement of adding Insert Mode Indication 

### ISSUE THREAD

**Issue by manoj-makkuboy** [caasiu/gnome-shell-extension-KeysIndicator#8]
How Cool It would be to add a Insert Mode indication to it?

**Comment by caasiu** [comment]
I don't think so, mate.
It doesn't detect any windows or input bars when you're typing.
What it does is globally detect the state of modifier keys(`Ctrl`, `Alt`, `Caps`, `Shift`)

**Comment by manoj-makkuboy** [comment]
I understand, Thank you So much. I have to say that you have built a wonderful extension which helps me a lot daily as my laptop don't have a physical Indicator.
